# Change these first
owner: ecosuite # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Web app
    url: https://app.ecosuite.io

assignees:
  - eljpsm

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ecosuite.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ecosuite/status-page/master/assets/ecosuite.svg
  name: Ecosuite Status
  # introTitle: "**Ecosuite Status** is the status page for Ecosuite."
  # introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/ecosuite/status-page). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
